/sensor_tf2_pkg/sensor_tf2_node:
  ros__parameters:
    lidar_main_tf2_flag: true
    lidar_imu_tf2_flag: true
    lidar_1_tf2_flag: true
    lidar_2_tf2_flag: true
    lidar_3_tf2_flag: true
    lidar_4_tf2_flag: true
    lidar_5_tf2_flag: true
    lidar_6_tf2_flag: true
    ins_tf2_flag: true
    gnss_tf2_flag: true
    radar_tf2_flag: true
    world_frame_id: /base_link
    lidar_main_frame_id: /lidar_front/points_xyzi
    lidar_imu_frame_id: /lidar_front/points_xyzi
    lidar_1_frame_id: /lidar_front/points_xyzi
    lidar_2_frame_id: /lidar_front/points_xyzi
    lidar_3_frame_id: /lidar_front/points_xyzi
    lidar_4_frame_id: /lidar_front/points_xyzi
    lidar_5_frame_id: /lidar_front/points_xyzi
    lidar_6_frame_id: /lidar_front/points_xyzi
    ins_frame_id: /lidar_front/points_xyzi
    gnss_frame_id: /lidar_front/points_xyzi
    radar_frame_id: /lidar_front/points_xyzi
    lidar_main_orintation_flag: true
    lidar_imu_orintation_flag: true
    lidar_1_orintation_flag: true
    lidar_2_orintation_flag: true
    lidar_3_orintation_flag: true
    lidar_4_orintation_flag: true
    lidar_5_orintation_flag: true
    lidar_6_orintation_flag: true
    ins_orintation_flag: true
    gnss_orintation_flag: true
    radar_orintation_flag: true
    base_2_lidar_main_linear_x: 0.0
    base_2_lidar_main_linear_y: 0.0
    base_2_lidar_main_linear_z: 0.0
    base_2_lidar_main_orintation_x: 0.0
    base_2_lidar_main_orintation_y: 0.0
    base_2_lidar_main_orintation_z: 0.0
    base_2_lidar_main_orintation_w: 0.0
    base_2_lidar_main_angle_x: 0.0
    base_2_lidar_main_angle_y: 0.0
    base_2_lidar_main_angle_z: 0.0
    base_2_lidar_imu_linear_x: 0.0
    base_2_lidar_imu_linear_y: 0.0
    base_2_lidar_imu_linear_z: 0.0
    base_2_lidar_imu_orintation_x: 0.0
    base_2_lidar_imu_orintation_y: 0.0
    base_2_lidar_imu_orintation_z: 0.0
    base_2_lidar_imu_orintation_w: 0.0
    base_2_lidar_imu_angle_x: 0.0
    base_2_lidar_imu_angle_y: 0.0
    base_2_lidar_imu_angle_z: 0.0
    base_2_lidar_1_linear_x: 0.0
    base_2_lidar_1_linear_y: 0.0
    base_2_lidar_1_linear_z: 0.0
    base_2_lidar_1_orintation_x: 0.0
    base_2_lidar_1_orintation_y: 0.0
    base_2_lidar_1_orintation_z: 0.0
    base_2_lidar_1_orintation_w: 0.0
    base_2_lidar_1_angle_x: 0.0
    base_2_lidar_1_angle_y: 0.0
    base_2_lidar_1_angle_z: 0.0
    base_2_lidar_2_linear_x: 0.0
    base_2_lidar_2_linear_y: 0.0
    base_2_lidar_2_linear_z: 0.0
    base_2_lidar_2_orintation_x: 0.0
    base_2_lidar_2_orintation_y: 0.0
    base_2_lidar_2_orintation_z: 0.0
    base_2_lidar_2_orintation_w: 0.0
    base_2_lidar_2_angle_x: 0.0
    base_2_lidar_2_angle_y: 0.0
    base_2_lidar_2_angle_z: 0.0
    base_2_lidar_3_linear_x: 0.0
    base_2_lidar_3_linear_y: 0.0
    base_2_lidar_3_linear_z: 0.0
    base_2_lidar_3_orintation_x: 0.0
    base_2_lidar_3_orintation_y: 0.0
    base_2_lidar_3_orintation_z: 0.0
    base_2_lidar_3_orintation_w: 0.0
    base_2_lidar_3_angle_x: 0.0
    base_2_lidar_3_angle_y: 0.0
    base_2_lidar_3_angle_z: 0.0
    base_2_lidar_4_linear_x: 0.0
    base_2_lidar_4_linear_y: 0.0
    base_2_lidar_4_linear_z: 0.0
    base_2_lidar_4_orintation_x: 0.0
    base_2_lidar_4_orintation_y: 0.0
    base_2_lidar_4_orintation_z: 0.0
    base_2_lidar_4_orintation_w: 0.0
    base_2_lidar_4_angle_x: 0.0
    base_2_lidar_4_angle_y: 0.0
    base_2_lidar_4_angle_z: 0.0
    base_2_lidar_5_linear_x: 0.0
    base_2_lidar_5_linear_y: 0.0
    base_2_lidar_5_linear_z: 0.0
    base_2_lidar_5_orintation_x: 0.0
    base_2_lidar_5_orintation_y: 0.0
    base_2_lidar_5_orintation_z: 0.0
    base_2_lidar_5_orintation_w: 0.0
    base_2_lidar_5_angle_x: 0.0
    base_2_lidar_5_angle_y: 0.0
    base_2_lidar_5_angle_z: 0.0
    base_2_lidar_6_linear_x: 0.0
    base_2_lidar_6_linear_y: 0.0
    base_2_lidar_6_linear_z: 0.0
    base_2_lidar_6_orintation_x: 0.0
    base_2_lidar_6_orintation_y: 0.0
    base_2_lidar_6_orintation_z: 0.0
    base_2_lidar_6_orintation_w: 0.0
    base_2_lidar_6_angle_x: 0.0
    base_2_lidar_6_angle_y: 0.0
    base_2_lidar_6_angle_z: 0.0
    base_2_ins_linear_x: 0.0
    base_2_ins_linear_y: 0.0
    base_2_ins_linear_z: 0.0
    base_2_ins_orintation_x: 0.0
    base_2_ins_orintation_y: 0.0
    base_2_ins_orintation_z: 0.0
    base_2_ins_orintation_w: 0.0
    base_2_ins_angle_x: 0.0
    base_2_ins_angle_y: 0.0
    base_2_ins_angle_z: 0.0
    base_2_gnss_linear_x: 0.0
    base_2_gnss_linear_y: 0.0
    base_2_gnss_linear_z: 0.0
    base_2_gnss_orintation_x: 0.0
    base_2_gnss_orintation_y: 0.0
    base_2_gnss_orintation_z: 0.0
    base_2_gnss_orintation_w: 0.0
    base_2_gnss_angle_x: 0.0
    base_2_gnss_angle_y: 0.0
    base_2_gnss_angle_z: 0.0
    base_2_radar_linear_x: 0.0
    base_2_radar_linear_y: 0.0
    base_2_radar_linear_z: 0.0
    base_2_radar_orintation_x: 0.0
    base_2_radar_orintation_y: 0.0
    base_2_radar_orintation_z: 0.0
    base_2_radar_orintation_w: 0.0
    base_2_radar_angle_x: 0.0
    base_2_radar_angle_y: 0.0
    base_2_radar_angle_z: 0.0
