/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "traffic_light_left_camera/camera_optical_link"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
